default_language_version:
  python: python3.9

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-json
    - id: check-merge-conflict
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: check-symlinks
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: trailing-whitespace

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    - id: pyupgrade
      args: [--py39-plus]

-   repo: https://github.com/adamchainz/django-upgrade
    rev: '1.12.0'
    hooks:
    -   id: django-upgrade
        args: [--target-version, "4.1"]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
      name: isort (python)

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      additional_dependencies:
      - flake8-bugbear
      - flake8-comprehensions
      - flake8-docstrings
      - flake8-tidy-imports
      - flake8-typing-imports
        # name: Flake8 on commit diff
        # description: This hook limits Flake8 checks to changed lines of code.
        # entry: bash
        # args: [-c, 'git diff HEAD | flake8 --diff']

-   repo: https://github.com/PyCQA/bandit/
    rev: 1.7.4
    hooks:
    - id: bandit
      args: ["-c", "pyproject.toml"]
      additional_dependencies: [ "bandit[toml]" ]

-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
    - id: codespell
      name: codespell
      # description: Checks for common misspellings in text files.
      # entry: codespell --ignore-words ignore-spelling-words.txt readme.md code.py
      # language: python
      # types: [text]
      args: [-I, .codespellignore]
      exclude: >
                (?x)^(
                    .*\.css\.map|
                    .*\.json|
                    .*\.js\.map|
                    .*\.lock|
                    .*\.min\.css\.map|
                    .*\.min\.js|
                    .*\.po|
                    .*\.pyc|
                    shCore.js|
                    \.tox
                )$

-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    - id: black

# -   repo: https://github.com/python-poetry/poetry
#     rev: '1.3.0'
#     hooks:
#     - id: poetry-check
#     - id: poetry-lock
